"use client";
import { useEffect,useState } from "react";
import { certificates } from "../data/content";

export function CertificateGallery(){
  const [active,setActive]=useState<number|null>(null);
  useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==="Escape")setActive(null);if(active!==null&&e.key==="ArrowRight")setActive((active+1)%certificates.length);if(active!==null&&e.key==="ArrowLeft")setActive((active-1+certificates.length)%certificates.length)};addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[active]);
  return <><div className="certificate-grid">{certificates.map((c,i)=><button className="certificate" key={c.title} onClick={()=>setActive(i)}><img className="cert-image" src={c.image} alt={`${c.title} certificate issued by ${c.issuer}`} loading="lazy"/><div><small>{c.issuer}</small><h2>{c.title}</h2><p>{c.date} · {c.skill}</p></div></button>)}</div>{active!==null&&<div className="modal" role="dialog" aria-modal="true" aria-label={certificates[active].title} onClick={()=>setActive(null)}><div className="modal-card certificate-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setActive(null)} aria-label="Close certificate">×</button><img className="cert-modal-image" src={certificates[active].image} alt={`${certificates[active].title} certificate`}/><div className="cert-details"><div><h2>{certificates[active].title}</h2><p>{certificates[active].issuer} · {certificates[active].date}</p></div><a className="button primary" href={certificates[active].pdf} target="_blank" rel="noreferrer">View PDF ↗</a></div>{certificates[active].courses&&<div className="certificate-courses"><strong>Courses completed</strong><div className="coursework">{certificates[active].courses.map(course=><span key={course}>{course}</span>)}</div></div>}<div className="modal-nav"><button onClick={()=>setActive((active-1+certificates.length)%certificates.length)}>← Previous</button><span>{active+1} / {certificates.length}</span><button onClick={()=>setActive((active+1)%certificates.length)}>Next →</button></div></div></div>}</>
}
